sudo: false
language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - |
    if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then
      composer config disable-tls true
      composer config secure-http false
    fi

install:
  - composer --working-dir fixtures --no-interaction update
  - composer --working-dir fixtures --no-interaction bin all update

script:
  - composer validate --no-interaction
  - php tests/root.php
  - php tests/sub.php

notifications:
  email: false
