sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  # From https://github.com/travis-ci/travis-ci/issues/5780#issuecomment-196308406
  - |
    function composer()
    {
      mv /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
      COMPOSER="$(which composer)"
      $COMPOSER "$@"
      STATUS=$?
      mv ~/xdebug.ini /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
      return $STATUS
    }

install:
  - composer update --working-dir fixtures --no-interaction
  - composer update --working-dir fixtures/vendor-bin/sub --no-interaction

script:
  - composer validate --no-interaction
  - php tests/root.php
  - php tests/sub.php

notifications:
  email: false
