sudo: false
language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - echo "$TRAVIS_PHP_VERSION"
  - |
    if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then
      composer config disable-tls true
      composer config secure-http false
      echo "holla"
    fi

install:
  - composer update --working-dir fixtures --no-interaction
  - composer update --working-dir fixtures/vendor-bin/sub --no-interaction

script:
  - composer validate --no-interaction
  - php tests/root.php
  - php tests/sub.php

notifications:
  email: false
