sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

matrix:
  fast_finish: true
  include:
    - php: '5.3'
      env: COMPOSER_FLAGS='--prefer-lowest'
  allow_failures:
    - php: nightly


cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  # From https://github.com/travis-ci/travis-ci/issues/5780#issuecomment-196308406
  - |
    XDEBUG_INI="/home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini"
    if [ ! -f "$XDEBUG_INI" ]; then
        return
    fi

    function composer()
    {
      mv $XDEBUG_INI ~/xdebug.ini
      COMPOSER="$(which composer)"
      $COMPOSER "$@"
      STATUS=$?
      mv ~/xdebug.ini $XDEBUG_INI

      return $STATUS
    }

install:
  - composer update --working-dir fixtures --no-interaction
  - composer update --working-dir fixtures/vendor-bin/sub --no-interaction

script:
  - composer validate --no-interaction
  - php tests/root.php
  - php tests/sub.php

notifications:
  email: false
